exports.Marker = {type: 'Marker', data: 'this is a marker token'};

exports.SCOPING_ELEMENTS = {
	html: [
		'applet',
		'caption',
		'html',
		'table',
		'td',
		'th',
		'marquee',
		'object'
	],
	math: [
		'mi',
		'mo',
		'mn',
		'ms',
		'mtext',
		'annotation-xml'
	],
	svg: [
		'foreignObject',
		'desc',
		'title'
	]
};

exports.LIST_SCOPING_ELEMENTS = {
	html: [
		'ol',
		'ul',
		'applet',
		'caption',
		'html',
		'table',
		'td',
		'th',
		'marquee',
		'object'
	],
	math: [
		'mi',
		'mo',
		'mn',
		'ms',
		'mtext',
		'annotation-xml'
	],
	svg: [
		'foreignObject',
		'desc',
		'title'
	]
};

exports.BUTTON_SCOPING_ELEMENTS = {
	html: [
		'button',
		'applet',
		'caption',
		'html',
		'table',
		'td',
		'th',
		'marquee',
		'object'
	],
	math: [
		'mi',
		'mo',
		'mn',
		'ms',
		'mtext',
		'annotation-xml'
	],
	svg: [
		'foreignObject',
		'desc',
		'title'
	]
};

exports.TABLE_SCOPING_ELEMENTS = {
	html: ['table', 'html']
};

exports.SELECT_SCOPING_ELEMENTS = {
	html: ['option', 'optgroup']
};

exports.FORMATTING_ELEMENTS = [
	'a',
	'b',
	'big',
	'code',
	'em',
	'font',
	'i',
	'nobr',
	's',
	'small',
	'strike',
	'strong',
	'tt',
	'u'
];
exports.SPECIAL_ELEMENTS = {
	html: [
		'address',
		'applet',
		'area',
		'article',
		'aside',
		'base',
		'basefont',
		'bgsound',
		'blockquote',
		'body',
		'br',
		'button',
		'caption',
		'center',
		'col',
		'colgroup',
		'dd',
		'details',
		'dir',
		'div',
		'dl',
		'dt',
		'embed',
		'fieldset',
		'figcaption',
		'figure',
		'footer',
		'form',
		'frame',
		'frameset',
		'h1',
		'h2',
		'h3',
		'h4',
		'h5',
		'h6',
		'head',
		'header',
		'hgroup',
		'hr',
		'html',
		'iframe',
		'img',
		'input',
		'isindex',
		'li',
		'link',
		'listing',
		'main',
		'marquee',
		'menu',
		'menuitem',
		'meta',
		'nav',
		'noembed',
		'noframes',
		'noscript',
		'object',
		'ol',
		'p',
		'param',
		'plaintext',
		'pre',
		'script',
		'section',
		'select',
		'source',
		'style',
		'summary',
		'table',
		'tbody',
		'td',
		'textarea',
		'tfoot',
		'th',
		'thead',
		'title',
		'tr',
		'track',
		'ul',
		'wbr',
		'xmp'
	],
	math: [
		'mi',
		'mo',
		'mn',
		'ms',
		'mtext',
		'annotation-xml'
	],
	svg: [
		'foreignObject',
		'desc',
		'title'
	]
};

exports.HTML_INTEGRATION_POINT_ELEMENTS = {
	math: ['annotation-xml'],
	svg: ['foreignObject', 'desc', 'title']
};

exports.MATHML_TEXT_INTEGRATION_POINT_ELEMENTS = {
	math: ['mi', 'mo', 'mn', 'ms', 'mtext']
};

exports.SPACE_CHARACTERS_IN = "\t\n\x0B\x0C\x20\u0012\r";
exports.SPACE_CHARACTERS = "[\t\n\x0B\x0C\x20\r]";
exports.SPACE_CHARACTERS_R = /^[\t\n\x0B\x0C \r]/;

exports.TABLE_INSERT_MODE_ELEMENTS = [
	'table',
	'tbody',
	'tfoot',
	'thead',
	'tr'
];

exports.ASCII_LOWERCASE = 'abcdefghijklmnopqrstuvwxyz';
exports.ASCII_UPPERCASE = exports.ASCII_LOWERCASE.toUpperCase();
exports.ASCII_LETTERS = "[a-zA-Z]";
exports.ASCII_LETTERS_R = /^[a-zA-Z]/;
exports.DIGITS = '0123456789';
exports.DIGITS_R = new RegExp('^[0123456789]');
exports.HEX_DIGITS = exports.DIGITS + 'abcdefABCDEF';
exports.HEX_DIGITS_R = new RegExp('^[' + exports.DIGITS + 'abcdefABCDEF' +']' );

// Heading elements need to be ordered 
exports.HEADING_ELEMENTS = [
	'h1',
	'h2',
	'h3',
	'h4',
	'h5',
	'h6'
];

exports.VOID_ELEMENTS = [
	'base',
	'command',
	'link',
	'meta',
	'hr',
	'br',
	'img',
	'embed',
	'param',
	'area',
	'col',
	'input',
	'source',
	'track'
];

exports.CDATA_ELEMENTS = [
	'title',
	'textarea'
];

exports.RCDATA_ELEMENTS = [
	'style',
	'script',
	'xmp',
	'iframe',
	'noembed',
	'noframes',
	'noscript'
];

exports.BOOLEAN_ATTRIBUTES = {
	'_global': ['irrelevant'],
	// Fixme?
	'style': ['scoped'],
	'img': ['ismap'],
	'audio': ['autoplay', 'controls'],
	'video': ['autoplay', 'controls'],
	'script': ['defer', 'async'],
	'details': ['open'],
	'datagrid': ['multiple', 'disabled'],
	'command': ['hidden', 'disabled', 'checked', 'default'],
	'menu': ['autosubmit'],
	'fieldset': ['disabled', 'readonly'],
	'option': ['disabled', 'readonly', 'selected'],
	'optgroup': ['disabled', 'readonly'],
	'button': ['disabled', 'autofocus'],
	'input': ['disabled', 'readonly', 'required', 'autofocus', 'checked', 'ismap'],
	'select': ['disabled', 'readonly', 'autofocus', 'multiple'],
	'output': ['disabled', 'readonly']
};

exports.ENCODINGS = [
	'ansi_x3.4-1968',
	'iso-ir-6',
	'ansi_x3.4-1986',
	'iso_646.irv:1991',
	'ascii',
	'iso646-us',
	'us-ascii',
	'us',
	'ibm367',
	'cp367',
	'csascii',
	'ks_c_5601-1987',
	'korean',
	'iso-2022-kr',
	'csiso2022kr',
	'euc-kr',
	'iso-2022-jp',
	'csiso2022jp',
	'iso-2022-jp-2',
	'',
	'iso-ir-58',
	'chinese',
	'csiso58gb231280',
	'iso_8859-1:1987',
	'iso-ir-100',
	'iso_8859-1',
	'iso-8859-1',
	'latin1',
	'l1',
	'ibm819',
	'cp819',
	'csisolatin1',
	'iso_8859-2:1987',
	'iso-ir-101',
	'iso_8859-2',
	'iso-8859-2',
	'latin2',
	'l2',
	'csisolatin2',
	'iso_8859-3:1988',
	'iso-ir-109',
	'iso_8859-3',
	'iso-8859-3',
	'latin3',
	'l3',
	'csisolatin3',
	'iso_8859-4:1988',
	'iso-ir-110',
	'iso_8859-4',
	'iso-8859-4',
	'latin4',
	'l4',
	'csisolatin4',
	'iso_8859-6:1987',
	'iso-ir-127',
	'iso_8859-6',
	'iso-8859-6',
	'ecma-114',
	'asmo-708',
	'arabic',
	'csisolatinarabic',
	'iso_8859-7:1987',
	'iso-ir-126',
	'iso_8859-7',
	'iso-8859-7',
	'elot_928',
	'ecma-118',
	'greek',
	'greek8',
	'csisolatingreek',
	'iso_8859-8:1988',
	'iso-ir-138',
	'iso_8859-8',
	'iso-8859-8',
	'hebrew',
	'csisolatinhebrew',
	'iso_8859-5:1988',
	'iso-ir-144',
	'iso_8859-5',
	'iso-8859-5',
	'cyrillic',
	'csisolatincyrillic',
	'iso_8859-9:1989',
	'iso-ir-148',
	'iso_8859-9',
	'iso-8859-9',
	'latin5',
	'l5',
	'csisolatin5',
	'iso-8859-10',
	'iso-ir-157',
	'l6',
	'iso_8859-10:1992',
	'csisolatin6',
	'latin6',
	'hp-roman8',
	'roman8',
	'r8',
	'ibm037',
	'cp037',
	'csibm037',
	'ibm424',
	'cp424',
	'csibm424',
	'ibm437',
	'cp437',
	'437',
	'cspc8codepage437',
	'ibm500',
	'cp500',
	'csibm500',
	'ibm775',
	'cp775',
	'cspc775baltic',
	'ibm850',
	'cp850',
	'850',
	'cspc850multilingual',
	'ibm852',
	'cp852',
	'852',
	'cspcp852',
	'ibm855',
	'cp855',
	'855',
	'csibm855',
	'ibm857',
	'cp857',
	'857',
	'csibm857',
	'ibm860',
	'cp860',
	'860',
	'csibm860',
	'ibm861',
	'cp861',
	'861',
	'cp-is',
	'csibm861',
	'ibm862',
	'cp862',
	'862',
	'cspc862latinhebrew',
	'ibm863',
	'cp863',
	'863',
	'csibm863',
	'ibm864',
	'cp864',
	'csibm864',
	'ibm865',
	'cp865',
	'865',
	'csibm865',
	'ibm866',
	'cp866',
	'866',
	'csibm866',
	'ibm869',
	'cp869',
	'869',
	'cp-gr',
	'csibm869',
	'ibm1026',
	'cp1026',
	'csibm1026',
	'koi8-r',
	'cskoi8r',
	'koi8-u',
	'big5-hkscs',
	'ptcp154',
	'csptcp154',
	'pt154',
	'cp154',
	'utf-7',
	'utf-16be',
	'utf-16le',
	'utf-16',
	'utf-8',
	'iso-8859-13',
	'iso-8859-14',
	'iso-ir-199',
	'iso_8859-14:1998',
	'iso_8859-14',
	'latin8',
	'iso-celtic',
	'l8',
	'iso-8859-15',
	'iso_8859-15',
	'iso-8859-16',
	'iso-ir-226',
	'iso_8859-16:2001',
	'iso_8859-16',
	'latin10',
	'l10',
	'gbk',
	'cp936',
	'ms936',
	'gb18030',
	'shift_jis',
	'ms_kanji',
	'csshiftjis',
	'euc-jp',
	'gb2312',
	'big5',
	'csbig5',
	'windows-1250',
	'windows-1251',
	'windows-1252',
	'windows-1253',
	'windows-1254',
	'windows-1255',
	'windows-1256',
	'windows-1257',
	'windows-1258',
	'tis-620',
	'hz-gb-2312'
];

exports.TAGMODES = {
	select: 'inSelect',
	td: 'inCell',
	th: 'inCell',
	tr: 'inRow',
	tbody: 'inTableBody',
	thead: 'inTableBody',
	tfoot: 'inTableBody',
	caption: 'inCaption',
	colgroup: 'inColumnGroup',
	table: 'inTable',
	head: 'inBody',
	body: 'inBody',
	frameset: 'inFrameset',
	html: 'beforeHead'
};

exports.SVGTagMap = {
	"altglyph": "altGlyph",
	"altglyphdef": "altGlyphDef",
	"altglyphitem": "altGlyphItem",
	"animatecolor": "animateColor",
	"animatemotion": "animateMotion",
	"animatetransform": "animateTransform",
	"clippath": "clipPath",
	"feblend": "feBlend",
	"fecolormatrix": "feColorMatrix",
	"fecomponenttransfer": "feComponentTransfer",
	"fecomposite": "feComposite",
	"feconvolvematrix": "feConvolveMatrix",
	"fediffuselighting": "feDiffuseLighting",
	"fedisplacementmap": "feDisplacementMap",
	"fedistantlight": "feDistantLight",
	"feflood": "feFlood",
	"fefunca": "feFuncA",
	"fefuncb": "feFuncB",
	"fefuncg": "feFuncG",
	"fefuncr": "feFuncR",
	"fegaussianblur": "feGaussianBlur",
	"feimage": "feImage",
	"femerge": "feMerge",
	"femergenode": "feMergeNode",
	"femorphology": "feMorphology",
	"feoffset": "feOffset",
	"fepointlight": "fePointLight",
	"fespecularlighting": "feSpecularLighting",
	"fespotlight": "feSpotLight",
	"fetile": "feTile",
	"feturbulence": "feTurbulence",
	"foreignobject": "foreignObject",
	"glyphref": "glyphRef",
	"lineargradient": "linearGradient",
	"radialgradient": "radialGradient",
	"textpath": "textPath"
};

exports.MATHMLAttributeMap = {
	definitionurl: 'definitionURL'
};

exports.SVGAttributeMap = {
	attributename:	'attributeName',
	attributetype:	'attributeType',
	basefrequency:	'baseFrequency',
	baseprofile:	'baseProfile',
	calcmode:	'calcMode',
	clippathunits:	'clipPathUnits',
	contentscripttype:	'contentScriptType',
	contentstyletype:	'contentStyleType',
	diffuseconstant:	'diffuseConstant',
	edgemode:	'edgeMode',
	externalresourcesrequired:	'externalResourcesRequired',
	filterres:	'filterRes',
	filterunits:	'filterUnits',
	glyphref:	'glyphRef',
	gradienttransform:	'gradientTransform',
	gradientunits:	'gradientUnits',
	kernelmatrix:	'kernelMatrix',
	kernelunitlength:	'kernelUnitLength',
	keypoints:	'keyPoints',
	keysplines:	'keySplines',
	keytimes:	'keyTimes',
	lengthadjust:	'lengthAdjust',
	limitingconeangle:	'limitingConeAngle',
	markerheight:	'markerHeight',
	markerunits:	'markerUnits',
	markerwidth:	'markerWidth',
	maskcontentunits:	'maskContentUnits',
	maskunits:	'maskUnits',
	numoctaves:	'numOctaves',
	pathlength:	'pathLength',
	patterncontentunits:	'patternContentUnits',
	patterntransform:	'patternTransform',
	patternunits:	'patternUnits',
	pointsatx:	'pointsAtX',
	pointsaty:	'pointsAtY',
	pointsatz:	'pointsAtZ',
	preservealpha:	'preserveAlpha',
	preserveaspectratio:	'preserveAspectRatio',
	primitiveunits:	'primitiveUnits',
	refx:	'refX',
	refy:	'refY',
	repeatcount:	'repeatCount',
	repeatdur:	'repeatDur',
	requiredextensions:	'requiredExtensions',
	requiredfeatures:	'requiredFeatures',
	specularconstant:	'specularConstant',
	specularexponent:	'specularExponent',
	spreadmethod:	'spreadMethod',
	startoffset:	'startOffset',
	stddeviation:	'stdDeviation',
	stitchtiles:	'stitchTiles',
	surfacescale:	'surfaceScale',
	systemlanguage:	'systemLanguage',
	tablevalues:	'tableValues',
	targetx:	'targetX',
	targety:	'targetY',
	textlength:	'textLength',
	viewbox:	'viewBox',
	viewtarget:	'viewTarget',
	xchannelselector:	'xChannelSelector',
	ychannelselector:	'yChannelSelector',
	zoomandpan:	'zoomAndPan'
};